### ISSUE TITLE
wrong balance being stored and displayed [debug and fix included 👍]

### ISSUE THREAD

**Issue by silto** [raydium-io/raydium-ui#11]
Hi!
I noticed an issue in your code that could lead to a faulty balance being detected for some tokens.
Here is the block of code where it is:
https://github.com/raydium-io/raydium-ui/blob/25abc9a451d9c9efe41780afa62cc9556a675e99/src/store/wallet.ts#L90-L146

When you get the balances, sometimes you get multiple times the balance for a same mintAddress. I'm not sure why, but I observed it when I did some tests (with USDC balance to be specific).

You apparently know about this  because you added a test here to update the balance if it is already added but equal to 0:

https://github.com/raydium-io/raydium-ui/blob/25abc9a451d9c9efe41780afa62cc9556a675e99/src/store/wallet.ts#L115-L127

the issue is that `tokenAccounts[mintAddress].balance` is a TokenAmount so testing `=== 0` will always be false.
So in the case where the balance is here twice, and is reported as 0 the first time, it will not update the second time.

A simple fix would be `tokenAccounts[mintAddress].balance.isNullOrZero()` which is implemented in TokenAmount
https://github.com/raydium-io/raydium-ui/blob/25abc9a451d9c9efe41780afa62cc9556a675e99/src/utils/safe-math.ts#L38-L40

Sorry for not doing a PR, I didn't want to fork the repo, but I guess this makes it pretty easy to fix.

Have a nice day!

**Comment by TimonPeng** [comment]
We fixed it already and will publish in a few hours.

**Comment by TimonPeng** [comment]
https://github.com/raydium-io/raydium-ui/commit/72d3c0c4efde46d8d035d521a57e77d04a6438b2#diff-c07d1f59eea37c701a8c47c6284dfaf13392a3bab5a68784c5d04dd5c78d46bcR116

Fixed always be false, and selected the account with the largest balance.

Will gradually go to use `AssociatedTokenAccount` to create new accounts in the future.
