### ISSUE TITLE
Slippage not being loaded at startup if already set [debug and fix included 👍]

### ISSUE THREAD

**Issue by silto** [raydium-io/raydium-ui#12]
Hi,

if the slippage has been set, it is stored in the LocalStorage as "RAY_SLIPPAGE"
When the setting store is loaded it fetches "RAYDIUM_SLIPPAGE", so it doesn't get the value that was set previously.

The bit of code where the problem is:
https://github.com/raydium-io/raydium-ui/blob/25abc9a451d9c9efe41780afa62cc9556a675e99/src/store/setting.ts#L5-L22

Sorry for not doing a PR, I didn't want to fork the repo, but I guess this makes it pretty easy to fix.

Have a nice day!

**Comment by TimonPeng** [comment]
Thanks for report, fixed will publish in few hours later.

**Comment by TimonPeng** [comment]
https://github.com/raydium-io/raydium-ui/commit/72d3c0c4efde46d8d035d521a57e77d04a6438b2#diff-1cf76189b82408c4654ebfe27c57b43bc279261c5642b3f4bcc0595a83393917R20
