### ISSUE TITLE
raydium.rpcpool.com/:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

### ISSUE THREAD

**Issue by Rowdy** [raydium-io/raydium-ui#34]
Tried to autofarm but I only see a circle of death.
![Screenshot 2021-07-01 at 20 55 19](https://user-images.githubusercontent.com/309042/124176358-16b49f00-daaf-11eb-8d81-f1132ba4d1b4.png)

raydium.rpcpool.com/:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
raydium-auto-farm.vercel.app/:1 Uncaught (in promise) Object
71bd241.js:2 Error: Number can only safely store up to 53 bits
    at r (4cb011e.js:2)
    at c.toNumber (4cb011e.js:2)
    at 7f5fda8.js:1
    at Array.forEach (<anonymous>)
    at 7f5fda8.js:1
    at f (inpage.js:141)
    at Generator._invoke (inpage.js:141)
    at Generator.next (inpage.js:141)
    at r (71bd241.js:2)
    at l (71bd241.js:2)
ne @ 71bd241.js:2

**Comment by maxidev** [comment]
+1

**Comment by maxidev** [comment]
can you please fix this? is there no way to get information

**Comment by TimonPeng** [comment]
rpc problem

**Comment by Jay54520** [comment]
> rpc problem

Should we run our own RPC to solve this?
