### ISSUE TITLE
true, true...

### ISSUE THREAD

**Issue by HulaTime** [raydium-io/raydium-ui#37]
https://github.com/raydium-io/raydium-ui/blob/7056fe3513cd3d1b232d7704bdff5aecb360afd3/src/plugins/web3.ts#L25
<img src="https://media.giphy.com/media/dXFKDUolyLLi8gq6Cl/source.gif" />

**Comment by Dakuan** [comment]
true true

**Comment by TimonPeng** [comment]
d8009df9a91d57e4e817dd2ef4e10aa96d338965
