### ISSUE TITLE
After command input "npm run start", there is no action in local host 

### ISSUE THREAD

**Issue by kihyun1118** [raydium-io/raydium-ui#40]
I'm new to JS and building local host.

After command inpu "npm run start", there is no action in local host.
In terminal, output is as follow:
---------------------------------------------------------------------------------
~/rush_prj/raydium-ui$ npm run start

> raydium-ui@1.0.0 start /home/noddown/rush_prj/raydium-ui
> nuxt start
   ╭─────────────────────────────────────────────╮
   │                                             │
   │   Nuxt @ v2.15.3                            │
   │                                             │
   │   ▸ Environment: production                 │
   │   ▸ Rendering:   client-side                │
   │   ▸ Target:      static                     │
   │                                             │
   │   Listening: http://192.168.219.102:3000/   │
   │                                             │
   ╰─────────────────────────────────────────────╯
ℹ Serving static application from dist/     
---------------------------------------------------------------------------------

I need your help! Thanks.

![pending_ui](https://user-images.githubusercontent.com/49215192/126900325-eb0b1266-2121-4a00-a6c7-cf4c5f8dbfbf.png)

**Comment by TimonPeng** [comment]
rpc problem
