### ISSUE TITLE
If there is only 3~5 seconds on the swap page, the following error is displayed.

### ISSUE THREAD

**Issue by fairyland0926** [raydium-io/raydium-ui#46]
![image](https://user-images.githubusercontent.com/72979420/132868959-911a0fae-6471-49a8-8c8f-ccc24bfe73b6.png)

**Comment by fairyland0926** [comment]
![image](https://user-images.githubusercontent.com/72979420/132869297-28d1b456-b375-4758-ac0b-01e0417045db.png)

**Comment by Zlt1012** [comment]
me too

**Comment by fairyland0926** [comment]
Since when does it not work?

**Comment by Zlt1012** [comment]
Do you know how to solve this problem？

**Comment by Zlt1012** [comment]
I couldn't think of a way to solve it

**Comment by emiliskiskis** [comment]
If you locally host this, make sure that `window.isSecureContext` is true. More about secure contexts: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts
