### ISSUE TITLE
[BUG] Number can only safely store up to 53 bits

### ISSUE THREAD

**Issue by shibainusolana** [raydium-io/raydium-ui#62]
Hello, we are have launch problem. Market ID was created, but we are can't create the pool because faced to js Number limit

![image](https://user-images.githubusercontent.com/95247974/149503004-e85a9d8a-f8d3-49f2-965c-b191ca0b0096.png)

![image](https://user-images.githubusercontent.com/95247974/149503056-9030964f-0f98-4d1c-8999-76a73c902c9a.png)

the market id 2L9LisBGHTtKTsNs6t4mv9ugcdK1kbgkuL4cmQNw9PYJ

**Comment by shibainusolana** [comment]
@rudy5348

**Comment by shibainusolana** [comment]
const value = "100000000000000000000000000000000000000000000000000000000000000";

const bn = new BN(value);
console.log(bn.toNumber());

Error: Number can only safely store up to 53 bits

**Comment by shibainusolana** [comment]
What a minimal decimals value? 0.000000000000001
15 numbers after zero?

**Comment by shibainusolana** [comment]
function divideBnToNumber(numerator, denominator) {
    const quotient = numerator.div(denominator).toString();
    const rem = numerator.umod(denominator);
    const gcd = rem.gcd(denominator);
    return quotient + rem.div(gcd).toString() / denominator.div(gcd).toString();
}

**Comment by shibainusolana** [comment]
function divideBnToNumber(numerator, denominator) {
    const quotient = numerator.div(denominator).toString();
    const rem = numerator.umod(denominator);
    const gcd = rem.gcd(denominator);
    return quotient + rem.div(gcd).toString() / denominator.div(gcd).toString();
}


![image](https://user-images.githubusercontent.com/95247974/149593888-69aaacc6-9d49-4982-8482-56119b8f29e4.png)

**Comment by shibainusolana** [comment]
https://solscan.io/tx/nWULgWU4XWmoafnd3Sw44SN5WTKzTJjwivPmGaBSPytTBhsjt2YKy4fvziXNhT9zBdNGaBEoeo2Y4vvwSAEHM5e

**Comment by shibainusolana** [comment]
![image](https://user-images.githubusercontent.com/95247974/149620789-6a013f5d-c94e-470c-aebc-d9043ae3bce8.png)

**Comment by TimonPeng** [comment]
The solana SPL program is designed amount to be u64 and this overflow value will not work.
